config/routes.rb
Ptrexchange::Application.routes.draw do

  get "home/welcome"
  get "home/index"
  get "home/search"
  get "home/paidreceipts"

  get "tickets/enter"
  get "receipts/enter"
  get "receipts/createmultiple"

  get "payment_notifications/create"
  get "admin/tickets/matched"
  get "admin/send_welcome_email"
  get "admin/send_matched_receipt_email"
  namespace :admin do
    resources :receipts, :tickets, :payment_notifications, :transactions
  end
  
  get "admin/index"
  match 'admin' => 'admin#index'
  resources :transactions
  resources :receipts
  resources :tickets
  resources :payment_notifications

  root :to => 'home#welcome'

end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
  attr_accessible :params, :status, :txn_id, :transaction_id, :time
  serialize :params
  after_create :mark_receipt_as_purchased

  private
  def mark_receipt_as_purchased
    if status.eql? "Completed"
      t = Transaction.find(transaction_id)
      t.update_attribute(:buyer_email, params[:payer_email])
      t.update_attribute(:status, "paid at paypal")
      r = Receipt.find(t.receipt_id)
      r.state = State.PAYPAL_PAID
      r.save
    end
  end
end

app/controllers/admin/payment_notifications_controller.rb
module Admin
class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]

  # GET /payment_notifications
  # GET /payment_notifications.json
  def index
    @payment_notifications = PaymentNotification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_notifications }
    end
  end

  # GET /payment_notifications/1
  # GET /payment_notifications/1.json
  def show
    @payment_notification = PaymentNotification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_notification }
    end
  end

  # GET /payment_notifications/new
  # GET /payment_notifications/new.json
  def new
    @payment_notification = PaymentNotification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_notification }
    end
  end

  # GET /payment_notifications/1/edit
  def edit
    @payment_notification = PaymentNotification.find(params[:id])
  end

  # POST /payment_notifications
  # POST /payment_notifications.json
  def create
    @payment_notification = PaymentNotification.new(params[:payment_notification])
    respond_to do |format|
      if @payment_notification.save
        format.html { redirect_to admin_payment_notification_path(@payment_notification), notice: 'payment notification was successfully created.' }
        format.json { render json: @payment_notification, status: :created, location: @payment_notification }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_notifications/1
  # PUT /payment_notifications/1.json
  def update
    @payment_notification = PaymentNotification.find(params[:id])

    respond_to do |format|
      if @payment_notification.update_attributes(params[:payment_notification])
        format.html { redirect_to @payment_notification, notice: 'Payment notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_notifications/1
  # DELETE /payment_notifications/1.json
  def destroy
    @payment_notification = PaymentNotification.find(params[:id])
    @payment_notification.destroy

    respond_to do |format|
      format.html { redirect_to admin_payment_notifications_url }
      format.json { head :no_content }
    end
  end
end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]

  # POST /payment_notifications
  # POST /payment_notifications.json
  def create
    PaymentNotification.create!(:params => params, :transaction_id => params[:invoice], :status => params[:payment_status], :txn_id => params[:txn_id])
    transaction = Transaction.find(params[:invoice])
    transaction.buyer_email = params[:payer_email]
    transaction.save
    render :nothing => true
  end
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/views/admin/payment_notifications/_form.html.erb
<%= form_for([:admin,@payment_notification]) do |f| %>
  <% if @payment_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_notification.errors.count, "error") %> prohibited this payment_notification from being saved:</h2>

      <ul>
      <% @payment_notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_area :params %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/payment_notifications/edit.html.erb
<h1>Editing payment_notification</h1>

<%= render 'form' %>

app/views/admin/payment_notifications/index.html.erb
<h1>Listing payment_notifications</h1>

<table>
  <tr>
    <th>Params</th>
    <th>transaction_id</th>
    <th>Status</th>
    <th>txn_id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_notifications.each do |payment_notification| %>
  <tr>
    <td><%= payment_notification.params %></td>
    <td><%= payment_notification.transaction_id %></td>
    <td><%= payment_notification.status %></td>
    <td><%= payment_notification.txn_id %></td>
    <td><%= link_to 'Show', admin_payment_notification_path(payment_notification) %></td>
    <td><%= link_to 'Edit', edit_admin_payment_notification_path(payment_notification) %></td>
    <td><%= link_to 'Destroy', admin_payment_notification_path(payment_notification), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment notification', new_admin_payment_notification_path %>

app/views/admin/payment_notifications/new.html.erb
<h1>New payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_notifications_path %>

app/views/admin/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Params:</b>
  <%= @payment_notification.params %>
</p>

<p>
  <b>transaction:</b>
  <%= @payment_notification.transaction_id %>
</p>

<p>
  <b>Status:</b>
  <%= @payment_notification.status %>
</p>

<p>
  <b>Transaction:</b>
  <%= @payment_notification.transaction_id %>
</p>


<%= link_to 'Edit', edit_admin_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', admin_payment_notifications_path %>