config/routes.rb
Ptrexchange::Application.routes.draw do

  get "home/welcome"
  get "home/index"
  get "home/search"
  get "home/paidreceipts"

  get "tickets/enter"
  get "receipts/enter"
  get "receipts/createmultiple"

  get "payment_notifications/create"
  get "admin/tickets/matched"
  get "admin/send_welcome_email"
  get "admin/send_matched_receipt_email"
  namespace :admin do
    resources :receipts, :tickets, :payment_notifications, :transactions
  end
  
  get "admin/index"
  match 'admin' => 'admin#index'
  resources :transactions
  resources :receipts
  resources :tickets
  resources :payment_notifications

  root :to => 'home#welcome'

end

app/models/home.rb
class Home
  attr_reader :email, :expiration_time, :purchased_date, :purchased_time, :rate
  attr_writer :email, :expiration_time, :purchased_date, :purchased_time, :rate

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def welcome
    session[:receipt_step] = nil
  end

  def paidreceipts
# select r.* from receipts r, transactions t where t.receipt_id = r.id and t.buyer_email = 'dgorodess@gmail.com' and t.status='paid at paypal'
    
    express_token = params[:token]
    if express_token
      details = EXPRESS_GATEWAY.details_for(express_token)
      @details = details
      @response = EXPRESS_GATEWAY.purchase(100, { :ip => request.remote_ip, :token => express_token, :payer_id => details.payer_id })
      t = Transaction.find(details.params["invoice_id"])
      t.buyer_email = details.email
      t.status = 'paid at paypal'
      t.save

      @receipts = Kaminari.paginate_array(Receipt.joins("JOIN transactions on transactions.receipt_id = receipts.id and transactions.status = 'paid at paypal' and transactions.buyer_email='#{t.buyer_email}'")).page(params[:page]).per(1)
    else
      @receipts = []
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  def search
    @transaction = Transaction.new

    @search = Search.new(Receipt, params)
    @receipts = Kaminari.paginate_array(Receipt.search(@search)).page(params[:page]).per(1)

    if @receipts.length > 0
      @transaction.receipt_id = @receipts[0].id
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @receipts }
      end
    else
      redirect_to tickets_enter_path(:rate => params[:rate], :ticket_time => { :year => params[:ticket_time][:year], :month => params[:ticket_time][:month], :day => params[:ticket_time][:day], :hour => params[:ticket_time][:hour], :minute => params[:ticket_time][:minute]})
    end
  end

  def time_from_options(which)
    which[:year] + "-" +("%02d" % which[:month]) + "-" + which[:day] + " " + which[:hour] + ":" + which[:minute] + "00"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_tag("/home/search", :method => "get") do %>
<table>
  <input type="hidden" name="page" value="1"/>
  <tr><th align="left"><%= label_tag(:rate, "Parking Zone Rate:") %><%= select_tag(:rate, options_for_select([['$1.75',1.75],['$3.50',3.5],['$5.75',5.75]])) %></th></tr>
  <tr><th align="left"><%= label_tag(:ticket_time, "Ticket Time:") %></th></tr>
  <tr><td colspan="2"><%= month_abbrev_select "ticket_time_month", "ticket_time[month]" %><%= day_select "ticket_time_day", "ticket_time[day]", Time.now.day %> at <%= hour_select("ticket_time_hour", "ticket_time[hour]", Time.now.hour) %>:<%= minute_select "ticket_time_minute", "ticket_time[minute]" %></td>

    <%= year_hidden "ticket_time_year", "ticket_time[year]" %>

  <tr><th colspan="2" align="left"><%= submit_tag("Search Meter Receipts") %></th></tr>
</table>
<% end %>

app/views/home/paidreceipts.html.erb
<style type="text/css">
.LARGER_METERRECEIPT_FONT {font-size:24pt;}
.GREEN {color: rgb(0,220,98);}
.SMALLGREEN {font-size:6pt;color: rgb(0,220,98);}

</style>

Your purchased receipts.<br>
Please contact the owner to arrange payment/delivery

<!--
<h3>details</h3>
<= @details.payer_id %>
<br>
<= @details.email %>
<br>
<= @details.params %>
<p>
<= @details.methods %>
<p>
<= @details.params["invoice_id"] %>
<p>
-->

<% @receipts.each do |receipt| %>

<table>
  <tr>
    <th>Owner of receipt email</th>
    <td><%= receipt.email %></td>
  </tr>
  <tr>
    <th>Owner of receipt cell</th>
    <td><%= receipt.cell_number %></td>
  </tr>
<tr>
<td colspan="2">
<table border="0" style="border-width: 1px; border-color:#000000;
border-style: solid;">
<tr>
<td colspan="5" class="GREEN">Valid at any pay box with same or lesser hourly RATE, until expired</td>
</tr>
<tr>
<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<td colspan="3">Motorcycle Plate No:_ _ _ _ _ _ _</td>
</tr>
<tr>
<th align="right">

<td rowspan="2" colspan="1" class="LARGER_METERRECEIPT_FONT">
<%= receipt.rate %>
</td>
<td align="left">Paid:$ <%= receipt.total_paid %>
<%= "%02d" % receipt.purchased_time.hour %>:<%= "%02d" % receipt.purchased_time.min %>
</tr>

</tr>
<tr>
<td>
<td>ID: 123456 <%= "%02d" % receipt.purchased_time.month %>/<%= "%02d" % receipt.purchased_time.day %>/12
</tr>
<tr>
<td>
<td border="1" style="border-width: 1px; border-color:#000000;border-style: dashed;" colspan="5"><table>

</tr>
<tr>
<td rowspan="2" class="LARGER_METERRECEIPT_FONT"><%= receipt.expiration_time.hour %>:<%= "%02d" % receipt.expiration_time.min %>
</td>
<td>
  <%= month_abbrev(receipt.expiration_time.mon) %><td rowspan="2" class="LARGER_METERRECEIPT_FONT"><%= "%02d" % receipt.expiration_time.day %>
<td>12
</tr>
<tr>
<td><%= receipt.expiration_time.hour < 12? "AM" : "PM" %>
<tr>
<td>Expiration Time
<td><td>Valid Date
</tr>
</table>
<tr><td><td>79780<td align="right">$<%= receipt.rate %>/hr
<tr><td class="GREEN" rowspan="2">LAZ<td colspan="3" class="SMALLGREEN">OPERATED BY LAZ PARKING&nbsp;&nbsp;&nbsp;chicagometers.com&nbsp;&nbsp;&nbsp;877.242.7901<br>PLACE THIS SIDE UP ON DASHBOARD CURBSIDE&nbsp;&nbsp;&nbsp;SEE DIRECTIONS ON REVERSE
</tr>
</table>
 

  </tr>
  <tr>
    <th>Photo</th>
  </tr>
  <tr>
    <td align="right" colspan-"2"><%= image_tag receipt.image.url %></td>
  </tr>
</table>
<% end %>

<%= paginate @receipts %>


<!--
for email - future reference 
    <td><a style="font: bold 11px Arial;text-decoration: none;background-color: #EEEEEE;color: #333333;padding: 2px 6px 2px 6px;border-top: 1px solid #CCCCCC;border-right: 1px solid #333333;border-bottom: 1px solid #333333;border-left: 1px solid #CCCCCC;" href="<= receipt.mailto_link >">I want this one</a></td>
-->

app/views/home/search.html.erb
<style type="text/css">
.LARGER_METERRECEIPT_FONT {font-size:24pt;}
.GREEN {color: rgb(0,220,98);}
.SMALLGREEN {font-size:6pt;color: rgb(0,220,98);}

</style>

<% @receipts.each do |receipt| %>

<table>
  <tr>
    <%= form_for(@transaction) do |f| %>
    <%= f.hidden_field :receipt_id %>
  </tr>
  <tr><td align="top">Pay $1 at PayPal to contact the owner. <td><%= f.submit "Pay $1 at PayPal", :type => :image, :src => "https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif" %>
</th></tr>
<% end %>
  <tr>
<td colspan="2">
<table border="0" style="border-width: 1px; border-color:#000000;
border-style: solid;">
<tr>
<td colspan="5" class="GREEN">Valid at any pay box with same or lesser hourly RATE, until expired</td>
</tr>
<tr>
<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<td colspan="3">Motorcycle Plate No:_ _ _ _ _ _ _</td>
</tr>
<tr>
<th align="right">

<td rowspan="2" colspan="1" class="LARGER_METERRECEIPT_FONT">
<%= receipt.rate %>
</td>
<td align="left">Paid:$ <%= receipt.total_paid %>
<%= "%02d" % receipt.purchased_time.hour %>:<%= "%02d" % receipt.purchased_time.min %>
</tr>

</tr>
<tr>
<td>
<td>ID: 123456 <%= "%02d" % receipt.purchased_time.month %>/<%= "%02d" % receipt.purchased_time.day %>/12
</tr>
<tr>
<td>
<td border="1" style="border-width: 1px; border-color:#000000;border-style: dashed;" colspan="5"><table>

</tr>
<tr>
<td rowspan="2" class="LARGER_METERRECEIPT_FONT"><%= receipt.expiration_time.hour %>:<%= "%02d" % receipt.expiration_time.min %>
</td>
<td>
  <%= month_abbrev(receipt.expiration_time.mon) %><td rowspan="2" class="LARGER_METERRECEIPT_FONT"><%= "%02d" % receipt.expiration_time.day %>
<td>12
</tr>
<tr>
<td><%= receipt.expiration_time.hour < 12? "AM" : "PM" %>
<tr>
<td>Expiration Time
<td><td>Valid Date
</tr>
</table>
<tr><td><td>79780<td align="right">$<%= receipt.rate %>/hr
<tr><td class="GREEN" rowspan="2">LAZ<td colspan="3" class="SMALLGREEN">OPERATED BY LAZ PARKING&nbsp;&nbsp;&nbsp;chicagometers.com&nbsp;&nbsp;&nbsp;877.242.7901<br>PLACE THIS SIDE UP ON DASHBOARD CURBSIDE&nbsp;&nbsp;&nbsp;SEE DIRECTIONS ON REVERSE
</tr>
</table>
 

  </tr>
  <tr>
    <th>Photo</th>
  </tr>
  <tr>
    <td align="right" colspan-"2"><%= image_tag receipt.image.url %></td>
  </tr>
</table>
<% end %>

<%= paginate @receipts %>


<h3>---- The Fine Print ----</h3>
After you submit payment, you will be able to view the<br>
email and/or the phone number of fellow Chicagoan that<br>
owns this receipt.  <p>

It's very likely that person may request an <br>
an additional amount for the receipt.<br>
(The suggested amount is $5 bucks )<br>
<p>

<!--
for email - future reference 
    <td><a style="font: bold 11px Arial;text-decoration: none;background-color: #EEEEEE;color: #333333;padding: 2px 6px 2px 6px;border-top: 1px solid #CCCCCC;border-right: 1px solid #333333;border-bottom: 1px solid #333333;border-left: 1px solid #CCCCCC;" href="<= receipt.mailto_link >">I want this one</a></td>
-->




app/views/home/welcome.html.erb
<tr class="white">
<td class="white">
<%= link_to image_tag("images/money1.jpg"), new_receipt_path %>
<td>O <%= link_to "Post your meter receipts.", new_receipt_path %>
<br>O <%= link_to "Earn $$$ for receipts.", new_receipt_path %>
<br>O <%= link_to "Fight back", new_receipt_path %>
<br>O <%= link_to "To Aggressive ticketing.", new_receipt_path %>

<tr class="white"><td>
<p>
<%= link_to image_tag("images/boot1.jpg"), home_index_path %>
<td>
O <%= link_to "Avoid the boot.", home_index_path %><br>
O <%= link_to "Find a meter receipt.", home_index_path %><br>
O <%= link_to "Get out of your ticket", home_index_path %><br>

<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>