config/routes.rb
Ptrexchange::Application.routes.draw do

  get "home/welcome"
  get "home/index"
  get "home/search"
  get "home/paidreceipts"

  get "tickets/enter"
  get "receipts/enter"
  get "receipts/createmultiple"

  get "payment_notifications/create"
  get "admin/tickets/matched"
  get "admin/send_welcome_email"
  get "admin/send_matched_receipt_email"
  namespace :admin do
    resources :receipts, :tickets, :payment_notifications, :transactions
  end
  
  get "admin/index"
  match 'admin' => 'admin#index'
  resources :transactions
  resources :receipts
  resources :tickets
  resources :payment_notifications

  root :to => 'home#welcome'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :email, :ticket_time, :rate, :cell_number, :amount
  validate :ticket_time_is_valid, :email_is_valid, :amount_is_valid

  # amount is usually 50 or 60 
  def amount_is_valid
    errors.add(:amount, 'ticket amount is not right.  Please double check') if amount < 40 || amount > 200
  end

  def ticket_time_is_valid
    errors.add(:ticket_time, 'ticket time is not Right, please double check') if ticket_time >= Time.now
  end

  def email_is_valid
    errors.add(:email, 'email is not Right, please double check') unless email =~ /^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$/
  end

end

app/controllers/admin/tickets_controller.rb
module Admin
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def matched
# select t.* from tickets t, receipts r where t.ticket_time between r.purchased_time and r.expiration_time and t.rate <= r.rate;

    @tickets = Ticket.select("distinct tickets.*").joins('JOIN receipts on tickets.ticket_time between receipts.purchased_time and receipts.expiration_time and tickets.rate <= receipts.rate')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/enter
  def enter
    @ticket = Ticket.new
    if params[:rate]
      @ticket.rate = params[:rate]
      @ticket.cell_number = params[:cell_number]
      @ticket.ticket_time = params[:ticket_time][:year] + "-" + params[:ticket_time][:month]+"-" + params[:ticket_time][:day] + " " + params[:ticket_time][:hour]+":"+params[:ticket_time][:minute]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to admin_ticket_path(@ticket), notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to admin_tickets_url }
      format.json { head :no_content }
    end
  end
end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/enter
  def enter
    @ticket = Ticket.new
    if params[:rate]
      @ticket.rate = params[:rate]
      @ticket.cell_number = params[:cell_number]
      @ticket.ticket_time = params[:ticket_time][:year] + "-" + params[:ticket_time][:month]+"-" + params[:ticket_time][:day] + " " + params[:ticket_time][:hour]+":"+params[:ticket_time][:minute]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to home_welcome_path, notice: 'Ticket was successfully created.' }
        format.json { render json: home_welcome_path, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/_form.html.erb
<%= form_for([:admin, @ticket]) do |f| %>
<table>
  <thead>
    <tr>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </tr>
  </thead>
  <tbody>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.text_field :email %></td>
    <tr>
      <th><%= f.label :cell_number %> (optional)</th>
      <td><%= f.text_field :cell_number %></td>
    <tr>
      <th><%= f.label :rate %></th>
      <td><%= f.select(:rate, options_for_select([['$1.75',1.75],['$3.50',3.5],['$5.75',5.75]])) %></td>
    </tr>
    <tr>
      <th><%= f.label :amount %></th>
      <td>$<%= f.number_field :amount, :step=>5, :min=>50, :max=>150.00 %></td>
    </tr>

    <tr>
      <th><%= f.label :ticket_time %></th>
      <td><%= f.datetime_select :ticket_time %></td>
    <tr>
      <th>
  <div class="actions">
    <%= f.submit %>
  </div>
  </tbody>
  </table>
<% end %>

app/views/admin/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

app/views/admin/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>id</th>
    <th>Email</th>
    <th>Cell Number</th>
    <th>Ticket Time</th>
    <th>Rate</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.id %></td>
    <td><%= ticket.email %></td>
    <td><%= ticket.cell_number %></td>
    <td><%= ticket.ticket_time.to_s(:long) %></td>
    <td><%= ticket.rate %></td>
    <td><%= ticket.amount %></td>
    <td><%= link_to 'Show', admin_ticket_path(ticket) %></td>
    <td><%= link_to 'Edit', edit_admin_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', admin_ticket_path(ticket), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/tickets/matched.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Id</th
    <th>Email</th>
    <th>Cell Number</th>
    <th>Ticket Time</th>
    <th>Rate</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.id %></td>
    <td><%= ticket.email %></td>
    <td><%= ticket.cell_number %></td>
    <td><%= ticket.ticket_time.to_s(:long) %></td>
    <td><%= ticket.rate %></td>
    <td><%= ticket.amount %></td>
    <td><%= link_to 'Show', admin_ticket_path(ticket) %></td>
    <td><%= link_to 'Edit', edit_admin_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', admin_ticket_path(ticket), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rate:</b>
  <%= @ticket.rate %>
</p>
<p>
  <b>Amount:</b>
  <%= @ticket.amount %>
</p>

<p>
  <b>Time:</b>
  <%= @ticket.ticket_time %>
</p>