config/routes.rb
Ptrexchange::Application.routes.draw do

  get "home/welcome"
  get "home/index"
  get "home/search"
  get "home/paidreceipts"

  get "tickets/enter"
  get "receipts/enter"
  get "receipts/createmultiple"

  get "payment_notifications/create"
  get "admin/tickets/matched"
  get "admin/send_welcome_email"
  get "admin/send_matched_receipt_email"
  namespace :admin do
    resources :receipts, :tickets, :payment_notifications, :transactions
  end
  
  get "admin/index"
  match 'admin' => 'admin#index'
  resources :transactions
  resources :receipts
  resources :tickets
  resources :payment_notifications

  root :to => 'home#welcome'

end

app/controllers/admin/transactions_controller.rb
module Admin
class TransactionsController < ApplicationController


  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @transaction.receipt_id = params[:receipt_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.save
    return_url = home_paidreceipts_url + "?buyer_email="+@transaction.buyer_email
#    return_url = transactions_url

    #    return_url = home_paidreceipts_url + "?buyer_email="+@transaction.buyer_email
    redirect_to Receipt.find(@transaction.receipt_id).paypal_url(@transaction.id, return_url, payment_notifications_url)
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to admin_transaction_path(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to admin_transactions_url }
      format.json { head :no_content }
    end
  end
end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController


  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @transaction.receipt_id = params[:receipt_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end


  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.save
    r = Receipt.find(@transaction.receipt_id)
    response = EXPRESS_GATEWAY.setup_purchase(100, express_options(@transaction, r))

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
    
  end

  private
  def express_options transaction, receipt
    options = {}
    options[:ip] = request.remote_ip
    options[:return_url] = home_paidreceipts_url
    options[:cancel_return_url] = home_welcome_url
    options[:transaction_id] = transaction.id
    options[:order_id] = transaction.id

    options[:items] = [{
      :name => "Contact Info for Meter receipt",
      :number => receipt.id,
      :quantity => 1,
      :amount => 100,
      :url => nil,
      :order_id => transaction.id,
      :description => "Contact Information for 1 meter receipt"
    }]

    options[:shipping] = 0
    options[:handling] = 0
    options[:tax] = 0
    options
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/admin/transactions/_form.html.erb
<%= form_for([:admin, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :receipt_id %><br />
    <%= f.number_field :receipt_id %>
  </div>
  <div class="field">
    <%= f.label :buyer_email %><br />
    <%= f.text_field :buyer_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_transaction_path(@transaction) %> |
<%= link_to 'Back', admin_transactions_path %>

app/views/admin/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>id</th>
    <th>Receipt</th>
    <th>Buyer email</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.id %></td>
    <td><%= transaction.receipt_id %></td>
    <td><%= transaction.buyer_email %></td>
    <td><%= transaction.status %></td>
    <td><%= link_to 'Show', admin_transaction_path(transaction) %></td>
    <td><%= link_to 'Edit', edit_admin_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', admin_transaction_path(transaction), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_admin_transaction_path %>

app/views/admin/transactions/new.html.erb
Purchase the contact info for this meter receipt<br>
Cost $1 ( PayPal )

<%= render 'form' %>

app/views/admin/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Receipt:</b>
  <%= @transaction.receipt_id %>
</p>

<p>
  <b>Buyer email:</b>
  <%= @transaction.buyer_email %>
</p>

<p>
  <b>Status:</b>
  <%= @transaction.status %>
</p>


<%= link_to 'Edit', edit_admin_transaction_path(@transaction) %> |
<%= link_to 'Back', admin_transactions_path %>